// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"blindly/internal/models"
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AddressInput struct {
	City    string `json:"city"`
	State   string `json:"state"`
	Country string `json:"country"`
}

// Return value after successful auth
type AuthPayload struct {
	AccessToken string       `json:"access_token"`
	User        *models.User `json:"user"`
}

type CommentFilterInput struct {
	PostID        *string    `json:"post_id,omitempty"`
	UserID        *string    `json:"user_id,omitempty"`
	ReplyToID     *string    `json:"reply_to_id,omitempty"`
	ParentOnly    *bool      `json:"parent_only,omitempty"`
	SearchContent *string    `json:"search_content,omitempty"`
	CreatedAfter  *time.Time `json:"created_after,omitempty"`
	CreatedBefore *time.Time `json:"created_before,omitempty"`
	MinLikes      *int32     `json:"min_likes,omitempty"`
}

type CommentsConnection struct {
	Comments   []*models.Comment `json:"comments"`
	PageInfo   *PageInfo         `json:"page_info"`
	TotalCount int32             `json:"total_count"`
}

type Connection struct {
	Chat               *models.Chat  `json:"chat"`
	Match              *models.Match `json:"match"`
	LastMessage        string        `json:"last_message"`
	UnreadMessages     int32         `json:"unread_messages"`
	PercentageComplete float64       `json:"percentage_complete"`
	ConnectionProfile  *UserPublic   `json:"connection_profile"`
}

type CreateCommentInput struct {
	PostID    string  `json:"post_id"`
	ReplyToID *string `json:"reply_to_id,omitempty"`
	Content   string  `json:"content"`
}

type CreatePostInput struct {
	Content string        `json:"content"`
	Media   []*MediaInput `json:"media,omitempty"`
}

type CreateReportInput struct {
	TargetID       string        `json:"target_id"`
	Reason         string        `json:"reason"`
	AdditionalInfo *string       `json:"additional_info,omitempty"`
	Media          []*MediaInput `json:"media"`
}

type CreateUserInput struct {
	Email       string        `json:"email"`
	Password    string        `json:"password"`
	FirstName   string        `json:"first_name"`
	LastName    string        `json:"last_name"`
	Dob         time.Time     `json:"dob"`
	Gender      *string       `json:"gender,omitempty"`
	Pfp         *string       `json:"pfp,omitempty"`
	Bio         *string       `json:"bio,omitempty"`
	Hobbies     []string      `json:"hobbies,omitempty"`
	Interests   []string      `json:"interests,omitempty"`
	UserPrompts []string      `json:"user_prompts,omitempty"`
	Photos      []string      `json:"photos,omitempty"`
	Address     *AddressInput `json:"address,omitempty"`
}

type MediaInput struct {
	ID        string    `json:"id"`
	URL       string    `json:"url"`
	Type      MediaType `json:"type"`
	CreatedAt string    `json:"created_at"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"has_next_page"`
	NextCursor      *string `json:"next_cursor,omitempty"`
	HasPreviousPage bool    `json:"has_previous_page"`
	PreviousCursor  *string `json:"previous_cursor,omitempty"`
}

type PersonalityTrait struct {
	Key   string `json:"key"`
	Value int32  `json:"value"`
}

type PersonalityTraitInput struct {
	Key   string `json:"key"`
	Value int32  `json:"value"`
}

type PostFilterInput struct {
	UserID        *string    `json:"user_id,omitempty"`
	SearchContent *string    `json:"search_content,omitempty"`
	CreatedAfter  *time.Time `json:"created_after,omitempty"`
	CreatedBefore *time.Time `json:"created_before,omitempty"`
	MinLikes      *int32     `json:"min_likes,omitempty"`
	MinComments   *int32     `json:"min_comments,omitempty"`
	MinViews      *int32     `json:"min_views,omitempty"`
	HasMedia      *bool      `json:"has_media,omitempty"`
}

type PostsConnection struct {
	Posts      []*models.Post `json:"posts"`
	PageInfo   *PageInfo      `json:"page_info"`
	TotalCount int32          `json:"total_count"`
}

type Query struct {
}

type RecommendationsResult struct {
	Items      []*RecommendedProfile `json:"items"`
	NextCursor *string               `json:"next_cursor,omitempty"`
	HasMore    bool                  `json:"has_more"`
	FetchedAt  time.Time             `json:"fetched_at"`
}

type RecommendedProfile struct {
	Profile            *UserPublic `json:"profile"`
	MatchScore         float64     `json:"match_score"`
	CompatibilityScore float64     `json:"compatibility_score"`
	CommonInterests    []string    `json:"common_interests"`
	DistanceKm         *float64    `json:"distance_km,omitempty"`
	Reason             *string     `json:"reason,omitempty"`
}

type SortInput struct {
	Field string    `json:"field"`
	Order SortOrder `json:"order"`
}

type SwipeResponse struct {
	Swipe *models.Swipe `json:"swipe"`
	Match *models.Match `json:"match,omitempty"`
}

type SwipedProfile struct {
	Profile *UserPublic   `json:"profile"`
	Swipe   *models.Swipe `json:"swipe"`
}

type UpdateCommentInput struct {
	CommentID string `json:"comment_id"`
	Content   string `json:"content"`
}

type UpdatePostInput struct {
	PostID  string        `json:"post_id"`
	Content *string       `json:"content,omitempty"`
	Media   []*MediaInput `json:"media,omitempty"`
}

type UpdateUserInput struct {
	FirstName         *string                  `json:"first_name,omitempty"`
	LastName          *string                  `json:"last_name,omitempty"`
	Dob               *time.Time               `json:"dob,omitempty"`
	Pfp               *string                  `json:"pfp,omitempty"`
	Bio               *string                  `json:"bio,omitempty"`
	Gender            *string                  `json:"gender,omitempty"`
	Hobbies           []string                 `json:"hobbies,omitempty"`
	Interests         []string                 `json:"interests,omitempty"`
	UserPrompts       []string                 `json:"user_prompts,omitempty"`
	PersonalityTraits []*PersonalityTraitInput `json:"personality_traits,omitempty"`
	Photos            []string                 `json:"photos,omitempty"`
	IsVerified        *bool                    `json:"is_verified,omitempty"`
	Address           *AddressInput            `json:"address,omitempty"`
}

type UserPublic struct {
	ID                string                `json:"id"`
	Name              string                `json:"name"`
	Pfp               string                `json:"pfp"`
	Bio               string                `json:"bio"`
	Dob               string                `json:"dob"`
	Gender            string                `json:"gender"`
	Hobbies           []string              `json:"hobbies"`
	Interests         []string              `json:"interests"`
	UserPrompts       []string              `json:"user_prompts"`
	PersonalityTraits []*PersonalityTrait   `json:"personality_traits"`
	Photos            []string              `json:"photos"`
	IsVerified        bool                  `json:"is_verified"`
	Extra             *models.ExtraMetadata `json:"extra,omitempty"`
	CreatedAt         time.Time             `json:"created_at"`
	IsOnline          bool                  `json:"is_online"`
	IsLocked          bool                  `json:"is_locked"`
	IsPoked           bool                  `json:"is_poked"`
	ChatID            string                `json:"chat_id"`
}

type UserVerificationInput struct {
	Media []*MediaInput `json:"media"`
}

type ActivityClass string

const (
	ActivityClassReceived ActivityClass = "RECEIVED"
	ActivityClassSent     ActivityClass = "SENT"
	ActivityClassAll      ActivityClass = "ALL"
)

var AllActivityClass = []ActivityClass{
	ActivityClassReceived,
	ActivityClassSent,
	ActivityClassAll,
}

func (e ActivityClass) IsValid() bool {
	switch e {
	case ActivityClassReceived, ActivityClassSent, ActivityClassAll:
		return true
	}
	return false
}

func (e ActivityClass) String() string {
	return string(e)
}

func (e *ActivityClass) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActivityClass(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActivityClass", str)
	}
	return nil
}

func (e ActivityClass) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActivityClass) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActivityClass) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CommentSortField string

const (
	CommentSortFieldCreatedAt CommentSortField = "CREATED_AT"
	CommentSortFieldLikes     CommentSortField = "LIKES"
)

var AllCommentSortField = []CommentSortField{
	CommentSortFieldCreatedAt,
	CommentSortFieldLikes,
}

func (e CommentSortField) IsValid() bool {
	switch e {
	case CommentSortFieldCreatedAt, CommentSortFieldLikes:
		return true
	}
	return false
}

func (e CommentSortField) String() string {
	return string(e)
}

func (e *CommentSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommentSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommentSortField", str)
	}
	return nil
}

func (e CommentSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommentSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommentSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MediaType string

const (
	MediaTypeImage MediaType = "IMAGE"
	MediaTypeVideo MediaType = "VIDEO"
	MediaTypeAudio MediaType = "AUDIO"
	MediaTypeFile  MediaType = "FILE"
)

var AllMediaType = []MediaType{
	MediaTypeImage,
	MediaTypeVideo,
	MediaTypeAudio,
	MediaTypeFile,
}

func (e MediaType) IsValid() bool {
	switch e {
	case MediaTypeImage, MediaTypeVideo, MediaTypeAudio, MediaTypeFile:
		return true
	}
	return false
}

func (e MediaType) String() string {
	return string(e)
}

func (e *MediaType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MediaType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MediaType", str)
	}
	return nil
}

func (e MediaType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MediaType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MediaType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PostSortField string

const (
	PostSortFieldCreatedAt PostSortField = "CREATED_AT"
	PostSortFieldLikes     PostSortField = "LIKES"
	PostSortFieldComments  PostSortField = "COMMENTS"
	PostSortFieldViews     PostSortField = "VIEWS"
)

var AllPostSortField = []PostSortField{
	PostSortFieldCreatedAt,
	PostSortFieldLikes,
	PostSortFieldComments,
	PostSortFieldViews,
}

func (e PostSortField) IsValid() bool {
	switch e {
	case PostSortFieldCreatedAt, PostSortFieldLikes, PostSortFieldComments, PostSortFieldViews:
		return true
	}
	return false
}

func (e PostSortField) String() string {
	return string(e)
}

func (e *PostSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PostSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PostSortField", str)
	}
	return nil
}

func (e PostSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PostSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PostSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortOrder string

const (
	SortOrderAsc  SortOrder = "ASC"
	SortOrderDesc SortOrder = "DESC"
)

var AllSortOrder = []SortOrder{
	SortOrderAsc,
	SortOrderDesc,
}

func (e SortOrder) IsValid() bool {
	switch e {
	case SortOrderAsc, SortOrderDesc:
		return true
	}
	return false
}

func (e SortOrder) String() string {
	return string(e)
}

func (e *SortOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrder", str)
	}
	return nil
}

func (e SortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
