// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"blindly/internal/models"
	"time"
)

type AddressInput struct {
	City    string `json:"city"`
	State   string `json:"state"`
	Country string `json:"country"`
}

// Return value after successful auth
type AuthPayload struct {
	AccessToken  string       `json:"access_token"`
	RefreshToken *string      `json:"refresh_token,omitempty"`
	ExpiresAt    *time.Time   `json:"expires_at,omitempty"`
	User         *models.User `json:"user"`
}

type CreateUserInput struct {
	Email             string                   `json:"email"`
	Password          string                   `json:"password"`
	FirstName         string                   `json:"first_name"`
	LastName          string                   `json:"last_name"`
	Dob               time.Time                `json:"dob"`
	Pfp               *string                  `json:"pfp,omitempty"`
	Bio               *string                  `json:"bio,omitempty"`
	Hobbies           []string                 `json:"hobbies,omitempty"`
	Interests         []string                 `json:"interests,omitempty"`
	UserPrompts       []string                 `json:"user_prompts,omitempty"`
	PersonalityTraits []*PersonalityTraitInput `json:"personality_traits,omitempty"`
	Photos            []string                 `json:"photos,omitempty"`
	Address           *AddressInput            `json:"address,omitempty"`
}

type Mutation struct {
}

type PersonalityTrait struct {
	Key   string `json:"key"`
	Value int32  `json:"value"`
}

type PersonalityTraitInput struct {
	Key   string `json:"key"`
	Value int32  `json:"value"`
}

type Query struct {
}

type UpdateUserInput struct {
	FirstName         *string                  `json:"first_name,omitempty"`
	LastName          *string                  `json:"last_name,omitempty"`
	Dob               *time.Time               `json:"dob,omitempty"`
	Pfp               *string                  `json:"pfp,omitempty"`
	Bio               *string                  `json:"bio,omitempty"`
	Hobbies           []string                 `json:"hobbies,omitempty"`
	Interests         []string                 `json:"interests,omitempty"`
	UserPrompts       []string                 `json:"user_prompts,omitempty"`
	PersonalityTraits []*PersonalityTraitInput `json:"personality_traits,omitempty"`
	Photos            []string                 `json:"photos,omitempty"`
	IsVerified        *bool                    `json:"is_verified,omitempty"`
	Address           *AddressInput            `json:"address,omitempty"`
}
