package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"blindly/internal/graph/model"
	"blindly/internal/models"
	"context"
)

// Swipe is the resolver for the swipe field.
func (r *mutationResolver) Swipe(ctx context.Context, targetID string, actionType models.SwipeType) (*model.SwipeResponse, error) {
	return r.SwipesResolver.Swipe(ctx, targetID, actionType)
}

// Recommendations is the resolver for the recommendations field.
func (r *queryResolver) Recommendations(ctx context.Context, cursor *string, limit *int32) (*model.RecommendationsResult, error) {
	return r.SwipesResolver.Recommendations(ctx, cursor, limit)
}

// MySwipes is the resolver for the mySwipes field.
func (r *queryResolver) MySwipes(ctx context.Context) ([]*model.SwipedProfile, error) {
	return r.SwipesResolver.MySwipes(ctx)
}
