package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"blindly/internal/graph/model"
	"blindly/internal/models"
	"context"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.AuthPayload, error) {
	return r.UserResolver.CreateUser(ctx, input)
}

// LoginWithPassword is the resolver for the loginWithPassword field.
func (r *mutationResolver) LoginWithPassword(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	return r.UserResolver.LoginWithPassword(ctx, email, password)
}

// RequestEmailLoginCode is the resolver for the requestEmailLoginCode field.
func (r *mutationResolver) RequestEmailLoginCode(ctx context.Context, email string) (bool, error) {
	return r.UserResolver.RequestEmailLoginCode(ctx, email)
}

// VerifyEmailLoginCode is the resolver for the verifyEmailLoginCode field.
func (r *mutationResolver) VerifyEmailLoginCode(ctx context.Context, email string, code string) (*model.AuthPayload, error) {
	return r.UserResolver.VerifyEmailLoginCode(ctx, email, code)
}

// UpdateMe is the resolver for the updateMe field.
func (r *mutationResolver) UpdateMe(ctx context.Context, input model.UpdateUserInput) (*models.User, error) {
	return r.UserResolver.UpdateMe(ctx, input)
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context) (*model.AuthPayload, error) {
	return r.UserResolver.RefreshToken(ctx)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	return r.UserResolver.Me(ctx)
}

// PersonalityTraits is the resolver for the personality_traits field.
func (r *userResolver) PersonalityTraits(ctx context.Context, obj *models.User) ([]*model.PersonalityTrait, error) {
	var traits []*model.PersonalityTrait
	if obj != nil {
		for k, v := range obj.PersonalityTraits {
			traits = append(traits, &model.PersonalityTrait{
				Key:   k,
				Value: int32(v),
			})
		}
	}
	return traits, nil
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) User(ctx context.Context, id string) (*models.User, error) {
	return r.UserResolver.User(ctx, id)
}
*/
